/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swisseph_Obama */

#ifndef _Included_swisseph_Obama
#define _Included_swisseph_Obama
#ifdef __cplusplus
extern "C" {
#endif

extern char SWE_OBAMA_OUT[];
extern char SWE_OBAMA_TMP[];

JNIEXPORT jint JNICALL Java_swisseph_SwissephTest_obama_1test_1main(JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
