/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swisseph_SweTest */

#ifndef _Included_swisseph_SweTest
#define _Included_swisseph_SweTest
#ifdef __cplusplus
extern "C" {
#endif

extern char SWE_OUT[];
extern char SWE_TMP[];

JNIEXPORT jint JNICALL Java_swisseph_SwephExp_swe_1test_1main(JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
